name: Worddynamics
favicon: null
layout_spectrum: 0.24422821588814259
typography_spectrum: 0.4287318221759051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0005160283762961626
  lightness: 0.19679193454794586
  saturation: 0.8956459432374686
  rhythmicContrast: 0.5360373412258923
purpose: []
